### ISSUE TITLE
When clicked on "close" button, minimize to tray

### ISSUE THREAD

**Issue by willyaranda** [baedert/corebird#111]
I am really used to click the "close" button when I finished reading timeline, but I do not want the app to really closed, but instead minimized to the system tray.

I think adding this option would be wonderful

**Comment by miko007** [comment]
don't make yourself a hustle. KDocker works just fine on Corebird.

**Comment by oblitum** [comment]
Sad for me how this has evolved. Close to tray is present in most instant messenger I have here on ArchLinux/Gnome 3.

- New Skype for Linux
- Whatsie for Whatsapp
- ScudCloud for Slack
- Gitter Client
- YakYak for Hangouts

CoreBird is the only one that I have that doesn't offer this and because of that I simply maintain Twitter close most of the time and just open occasionally to check contents and close it again, preferring to get notifications from smartphone instead.

**Comment by laurentdinclaux** [comment]
"From a user perspective it's just very weird that closing the window does not really close the window."

It does close the window but just not the app, nothing wrong with that.
Slack and telegram app do it too.

**Comment by Vistaus** [comment]
@oblitum @laurentdinclaux Except that the GTK tray is removed from upstream GTK code, so how do you support a non-existent tray?

**Comment by oblitum** [comment]
@Vistaus It wasn't at the time I made that comment. I don't use upstream but if all applications I use currently on ArchLinux/Gnome3 are going to lose their tray icons, this change is going to be a big mess.

**Comment by Vistaus** [comment]
@oblitum It was removed 3 days after you made that comment ;) But I was pointing it out right now to point out the future. And yes, it's going to be a big mess if you rely on tray icons.

**Comment by oblitum** [comment]
@Vistaus also, formerly, no one here was asking support for non-existing/unfeasible features, just for what everyone sees implemented by many applications. Besides messengers, there are lots of programs that offers this.

**Comment by Vistaus** [comment]
@oblitum Doesn't matter if others have support for it, esp. when they're gonna lose their tray icon as well. I was just pointing out that without a GTK tray, there's no point in supporting it since Corebird is aimed at GTK-based desktops.

**Comment by oblitum** [comment]
@Vistaus it **did** matter. As for whether it **won't** matter anymore, dunno. My last comment was to point that starting by arguing with the past discussion (previous state) in face of new information may have no point.

**Comment by oblitum** [comment]
@Vistaus regardless how you shared the insight, thanks for it.

**Comment by oblitum** [comment]
@Vistaus I just can't believe I'm gonna lose all these tray icons (Steam, DropBox, Virtual Machine Manager, ...).

**Comment by ManuelSchneid3r** [comment]
Please rethink your decision. Just because shitty gnome does not like tray does not mean people dont like the tray. Gnome UX is horrible. No need to adapt here. Further there are plenty of other DEs out there, all of them like trays. Even rudimentary ones like i3, awesome and openbox do simply because it is an essential part of a productive operating system. Nobody knows why Gnome is going this way. 

> From a user perspective it's just very weird that closing the window does not really close the window.

imo this is perfectly normal. Closing is moving to background. I dont want to see anything but that 24x24 px. Minimizing is different.

**Comment by ManuelSchneid3r** [comment]
I had to add this: Since they released crappy Gnome 3 the have never had more than 10% market share. Not that the were top dog before with about 50%. Let the numbers speak. Gnome sucks. Please give us a tray.

![image](https://user-images.githubusercontent.com/3252315/37407794-db85a8e0-279a-11e8-842b-d1e7d8d0e631.png)

**Comment by Vistaus** [comment]
@ManuelSchneid3r It's not about GNOME, it's about GTK. GTK is the one who dropped support for the system tray and because GNOME is built with GTK, they dropped the system tray as well.
