### ISSUE TITLE
Tweet details should contain a larger version of the inline media

### ISSUE THREAD

**Issue by baedert** [baedert/corebird#199]
There's enough space so the preview should just show a smaller version of the whole image instead of a cut-out piece.

**Comment by Suero** [comment]
There should be an option to show the full images like Birdie does, instead of this banner view that is now. That is currently the only reason why I don't use this over Birdie, having to click the thumbnails to even see what it is, that is annoying. I understand that some people like it the way that it is now, that is why I am suggest a settings toggle for it.
