### ISSUE TITLE
Images  are scaled in width and not in height

### ISSUE THREAD

**Issue by jbahillo** [baedert/corebird#278]
HI: perhaps this is intended, but it provokes images to be distorted

![captura de pantalla de 2014-11-21 12 44 15](https://cloud.githubusercontent.com/assets/2781605/5141920/20ddb19a-717c-11e4-94f7-0b45c4703293.png)

I think they should remain centered and with original width, or at least mantain the original height-width ratio

**Comment by hobarrera** [comment]
I can't understand how this, being the default behaviour and visible since opening corebird for the first time, has been an open issue for over six months:

![2015-04-27t03 52 45 552277244-0300](https://cloud.githubusercontent.com/assets/730811/7342910/0eb39418-ec91-11e4-9fec-785762f7358c.png)

**Comment by baedert** [comment]
And I can't believe people keep maximizing a window containing a single listview? 

You can't make it resize smoothly when resizing the window without keeping the entire image in ram all the time, it would suck for multiple media, everybody in public can always see the image, etc. This "bug" is much older, see #199 or #198.

**Comment by hobarrera** [comment]
> And I can't believe people keep maximizing a window containing a single listview? 

I don't manually resize it, I'm merely not using a composing (or floating) window manager, so this is the default behaviour (I'm using i3 in this case).

For things like pidgin, I keep the contact list and conversation view side-by-side, but there's really nothing useful to keep right next to corebird (since it does all I need in one window ;) ).

Maybe an alternative approach is to display a second column with something else if width > X. (Mentions? Another tab?).

**Comment by hobarrera** [comment]
I noticed that all dupes of this issue have been closed. Is this being tracked anywhere?

**Comment by baedert** [comment]
master scales them to the window width, unless that would scale > 1.0. I'm pondering restricting the height + cropping and adding a indicator for the missing image content.

**Comment by hobarrera** [comment]
I can confirm this works perfectly on master. Thanks.
