### ISSUE TITLE
No more action from the tweet list.

### ISSUE THREAD

**Issue by hfiguiere** [baedert/corebird#295]
Also probably related to #293, no more reply / rt / fav from the tweet list. This is a serious regression.

**Comment by hfiguiere** [comment]
Seems like a deliberate change looking a the git history.

**Comment by baedert** [comment]
Yes. They are available through right-clicking tweets now.

**Comment by hfiguiere** [comment]
So not discoverable. Nothing was wrong with how it was before. Even with the single click snafu.

**Comment by baedert** [comment]
Lots of things were wrong with the old hover buttons, that's why I replaced them. I don't do stuff like that because it's so much fun.

**Comment by hfiguiere** [comment]
But then the context menu is not discoverable, so it is failing that way more than before.

The only problem I saw with the old hover buttons is that retweet caused a lot of time to lose focus for keyboard navigation....

**Comment by baedert** [comment]
Well, other problems are e.g. that they cover(ed) content (seems to be still an issue in hidpi according to #32), which is by the way the reason for the rather large gap between author and text which I've just decreased a bit, they can't have tooltips ([upstream bug](https://bugzilla.gnome.org/show_bug.cgi?id=742744)).
They didn't fit in with hover background transitions (like you have them in recent adwaita versions) because the overlay needs to have the same background as the list row, so text beneath it gets properly covered. 
The active buttons/indicators for retweeted/favorited tweets never really lined up with the other text (because they were the same buttons as used to retweet/favorite, thus in an overlay) and WOW getting even to that point was a lot of ugly code (and guesswork...).

Right-clickable listrows are indeed unusual and I'm not sure how to solve *that*, or if it needs solving at all, but I'm so far pretty ok with the tradeoffs.
