### ISSUE TITLE
Certain text labels increase the minimum window size

### ISSUE THREAD

**Issue by Lyude** [baedert/corebird#345]
So this is a problem I've seen in a couple places in Corebird, I'm not sure about where all of the other spots are where this happens but I've got one here that's easily reproducible. So, basically it looks like certain GtkLabels in use on Corebird end up increasing the minimum window size because the text in them is too long, and they don't have any other fallback when the text won't fit in the window. Having your window force resize itself can be somewhat annoying after a while. Here's a good example you can reproduce:

- Set the window width to 480, height to 611
- Scroll around on your timeline for a bit. Maybe check out some of my rad tweets.
- Go from your timeline to this tweet [here](https://twitter.com/_Lyude/status/583620671663710208)
- Window width automatically expands to 523. You can no longer make the width any smaller then that without restarting Corebird.

In situations like this, I think it would be best to have the tag allow wrapping or to ellipse the end of the tag when the full text can't be displayed. Enabling the "wrap" property with gtk-inspector allows you to once again shrink the size of the window, while keeping all of the text still visible. As I find more labels that cause this, I'll try adding them to this issue.

**Comment by baedert** [comment]
The problem is, as far as I can see (and observe by commenting out that portion of the code), the "time, date, via <client>" label, which just gets pretty long if the client it "Twitter for Android". The *general* problem is, of course, that we display totally unknown text in non-wrapping, non-ellipsizing labels but for some of them (i.e. screen_names or names, or list names), both of them aren't really an option (iirc, list names even ellipsize because they can get soooo long).

I think just ellipsizing at the end (thus cutting of a part of the client and not of the date/time) is just fine in this case.

**Comment by Lyude** [comment]
![screenshot from 2015-04-02 10 09 24](https://cloud.githubusercontent.com/assets/1527057/6965550/6d1b6154-d920-11e4-9d18-8666ec69ea6b.png)
That sounds fine, tbh though wrap doesn't look too bad here
