### ISSUE TITLE
Theming issue on elementary OS

### ISSUE THREAD

**Issue by sikatsuket** [baedert/corebird#355]
I found Corebird's appearance on elementary OS is a bit different with when it's on GNOME. First, the separator line between tweets has quite distracting color.

![comparing](https://cloud.githubusercontent.com/assets/11985889/7193761/6e9813f0-e4cf-11e4-883e-b2a9004ddc02.png)

Other than that, when I compose a tweet that contains hashtag or mentions someone, the text turns white. And it becomes unseen because the background is white too.

![comparing-1](https://cloud.githubusercontent.com/assets/11985889/7193895/cb1ab0e6-e4d0-11e4-92c9-b44e42b5e37e.png)

I assume you don't have really much time for using elementary OS :)

**Comment by baedert** [comment]
https://github.com/baedert/corebird/blob/b1164cd0e5338f1379436aaa88013ae25bc04a91/src/widgets/CompletionTextView.vala#L40
I guess yours doesn't.

**Comment by sikatsuket** [comment]
Wait, wait... Actually, I don't know about programming. I don't understand what you said. Were you trying to say this "issue" can be fixed? What I have to do, to do it?

**Comment by baedert** [comment]
invisible hashtags: Well yes. We currently just take the color of `*:link`, but if that's not set we just get white which produces white on white for you. We could just use our own color, but then they won't look exactly like links in labels (or like links at all...).

separator color: The current color is just `alpha (@borders, 0.4)` so it depends on whatever the gtk+ theme thinks `@borders` is (and if that's unset, we get black IIRC).

**Comment by sikatsuket** [comment]
So, can you give me practical instruction on how to fix it? You know, like edit some configuration files, add some lines, and so on. I wonder that the issue caused by elementary, so we need to modify some part of it, right?

Sorry, I'm too dumb to figure it out by myself.

**Comment by baedert** [comment]
Separators in elementary are #959595, so if that works out "perfectly", the result would be
![screenshot from 2015-04-17 15-40-29](https://cloud.githubusercontent.com/assets/887764/7203821/c86422d6-e51d-11e4-8727-971351bd6734.png)

For missing link colors, we can just fall back to Adwaita's link color in case we get completely opaque white (but of course, that could be a valid link color...). That would look like: 
![screenshot from 2015-04-17 16-20-29](https://cloud.githubusercontent.com/assets/887764/7203857/30d922e4-e51e-11e4-8d8a-7b70bb980047.png)
Consistency with normal links in labels is no concern in this case, since they aren't styled at all anyway (I would look up now if they are styled or not, but wow launchpad is horrible. I'm just gonna take your screenshots as confirmation).
