### ISSUE TITLE
[Feature Request] Add support for twister-core

### ISSUE THREAD

**Issue by rodneyrod** [baedert/corebird#372]
http://twister.net.co/ is working on creating a P2P microblogging platform, it would be really great if there was support from a 3rd party client like corebird for it too.

**Comment by baedert** [comment]
See, I only have one life and I really can't spend it all on porting corebird to support 53 different services and protocols. I've said this multiple times already, I never wrote corebird with the idea in mind that it will ever support anything but Twitter itself. *I* will never work on this.

**Comment by rodneyrod** [comment]
Well, I think that they're working on a Twitter compatible API, so it wouldn't involve much work at all.

**Comment by seboss666** [comment]
Yeah, but Twitter API support is not already complete in Corebird (and some features may not be public at all...). I prefer to have a free software that runs very well on a single network than a "toolbox" with many parts missing for multiple ones.

That said, it's free software : you may find a guy, or push yourself to fork and adapt to twister :P

**Comment by rodneyrod** [comment]
>That said, it's free software : you may find a guy, or push yourself to fork and adapt to twister :P

This is true, however the search is made harder to find one that is those and who also knows Vala :p

**Comment by baedert** [comment]
And I really like software people use not because it's free, but because it's good. That's why I don't understand people creating a twitter clone just for the sake of having a free twitter clone (not saying twister-core is a twitter clone, but if you only use the "twitter compatible API", that's what you get. Same problem with gnusocial). To really "support" $service, you need a client that supports all the features it provides, has UI for it, etc, not just the common twitter subset.

And of course it would be a lot of work, you're basically doubling the testing space *everywhere*. That really only works if you have multiple developers and at least one uses that service daily.

> Twitter API support is not already complete in Corebird (and some features may not be public at all...).

WHOA. I have feelings.
