### ISSUE TITLE
Feature request: Add option to hide inappropriate content by default

### ISSUE THREAD

**Issue by Lyude** [baedert/corebird#400]
Self explanatory, and honestly something I'd really find useful on a daily basis. Having people post inappropriate stuff with absolutely no indicator beforehand on an account that's usually SFW is really obnoxious when you're using your computer in public.
You'd probably be able to do something like replace the images with a ⚠ until the user clicks on it and confirms that they want to see the image.

**Comment by baedert** [comment]
Do I understand this correctly that the inline preview strip is not the problem, but that you click on the image without knowing it's nsfw? i.e. indicating the nsfw-ness is enough and the click you're talking about is just the normal click that would also immediately show the dialog?

**Comment by Lyude** [comment]
The preview strip is the problem because with an option like this we
wouldn't want to show any part of the image until the user explicitly opens
it. Also it's not always possible to tell the content of the image just
from the preview strip

**Comment by baedert** [comment]
Ok, I didn't want to implement this in master whlie reworking the media display in another brancht, so I have this locally atm in `wip/baedert/full-media`:
![screenshot from 2015-11-12 18-37-56](https://cloud.githubusercontent.com/assets/887764/11125893/a495dfea-896c-11e5-9804-6b59bb282e89.png)

I'm pondering giving that button its relief back and making it dimmed maybe, but the real issue is that both the label and the button seem kind of lost.

**Comment by Lyude** [comment]
This looks awesome actually (sorry for the late response, was looking through bugs to see if something I was about to report had been reported yet and noticed you did respond to this ;)

**Comment by baedert** [comment]
Ok, just merged this into master, with an appropriate setting. The setting does not get appliied immediately ATM.

**Comment by baedert** [comment]
Fixed in master.
