### ISSUE TITLE
Create a flatpak repository

### ISSUE THREAD

**Issue by marciosr** [baedert/corebird#485]
I don't know if that is the right way to ask that, but would be nice have a xdg-app repo to corebird-git, turning more easy test developer versions, keeping the stable one at the same time. 

https://wiki.gnome.org/Projects/SandboxedApps/NightlyBuilds

https://wiki.gnome.org/Projects/SandboxedApps

**Comment by baedert** [comment]
You can't open uris with other apps yet, so the very first thing you want to do (set up an account) doesn't work.

**Comment by marciosr** [comment]
oh, I didn't know that. I hope they could implement that soon.

Thanks for the reply.

**Comment by baedert** [comment]
FWIW here's a json config file for `xdg-app-builder`: https://github.com/baedert/corebird-xdg-app. Setting up an account works if you click request pin, then close the error dialog, then just copy the link into another browser. Of course, links don't work, and I'm currently passing `--disable-video` at configure time in the json file since I didn't have time into looking why gstreamer doesn't want to work.

**Comment by nedrichards** [comment]
Fwiw you can now open URIs with other apps using flatpak.

**Comment by baedert** [comment]
I haven't been able to properly test that since the async open-uri portal in support was broken. It's since been fixed but the runtime hasn't been updated apparently.

**Comment by baedert** [comment]
Okay tried it again with the gnome nightly sdk/platform and it works.

**Comment by baedert** [comment]
I've updated https://github.com/baedert/corebird-flatpak with instructions for installing and an actual repo fwiw
