### ISSUE TITLE
App crashes when trying to view media

### ISSUE THREAD

**Issue by jc00ke** [baedert/corebird#555]
The video in [this tweet](https://twitter.com/Jacobnbc/status/735509460932648964) crashes the app. The video is downloaded then, poof!

Built on ca2fdab

Interestingly enough, when I run `corebird` like this:
`GST_DEBUG=6 GST_DEBUG_NO_COLOR=1 corebird > log-debug.txt 2>&1` the video does not crash the app.

When I run it like this:
```
➜ ~ corebird > log-no-debug.txt 2>&1
fish: “corebird > log-no-debug.txt 2>&1” terminated by signal SIGABRT (Abort)
```

[log-debug.txt.zip](https://github.com/baedert/corebird/files/282452/log-debug.txt.zip)

[log-no-debug.txt](https://github.com/baedert/corebird/files/282453/log-no-debug.txt)

**Comment by baedert** [comment]
That's happening because we're now playing the HLS version of twitter videos (no other option, at least starting from august...). It works here though, so I guess that's another gstreamer problem. the debug log doesn't contain the ERROR line from the no-debug output though (which is the only interesting line there, the rest is just the API limit).

Does `gst-play-1.0 --videosink=gtksink "https://video.twimg.com/ext_tw_video/735377290754990080/pu/pl/bw5NhmfraFSwMghH.m3u8"` exhibit the same problem?

**Comment by jc00ke** [comment]
```
➜ ~ gst-play-1.0 --videosink=gtksink "https://video.twimg.com/ext_tw_video/735377290754990080/pu/pl/bw5NhmfraFSwMghH.m3u8"
Press 'k' to see a list of keyboard shortcuts.
Now playing https://video.twimg.com/ext_tw_video/735377290754990080/pu/pl/bw5NhmfraFSwMghH.m3u8
Redistribute latency...

**ffering... 100%  
ERROR:gstadaptivedemux.c:1095:gst_adaptive_demux_find_stream_for_pad: code should not be reached
fish: “gst-play-1.0 --videosink=gtksin…” terminated by signal SIGABRT (Abort)
➜ ~ 
```

Ubuntu picked up on the crash too, here's the screenshot (I can rerun and attach a dump, you'll have to tell me where to look for it)
![_ubuntu_004](https://cloud.githubusercontent.com/assets/18191/15549914/b72cc886-2263-11e6-8093-dadf81223375.png)

**Comment by baedert** [comment]
This is apparently fixed in gstreamer 1.8.1: https://bugzilla.gnome.org/show_bug.cgi?id=764404

**Comment by jc00ke** [comment]
Gotcha. Hopefully I'll get updated soon.

**Comment by jc00ke** [comment]
`gstreamer` was updated and the issue is no longer present.
