### ISSUE TITLE
Cannot open clickable url

### ISSUE THREAD

**Issue by doihara** [baedert/corebird#581]
Running version 1.21 on Kubuntu 16.04 with GTK 3.18.9-1. 
If I click a link in corebird, nothing seems to be happening. In terminal it shows the following error message:

`(corebird:2859): Gtk-WARNING **: Unable to show 'http://to.welt.de/ED81UYk': Operation not supported   `

In fact, after the installation, even the "request pin" didn't work. I had to manually copy the link in a browser to authorize permission in Twitter. It popped up a meesage window saying " Operation not supported." 
I check my default application of browser is Firefox. 
I have no idea what else should I do in order to make it work. Could anyone please help me?
Thank you!

**Comment by baedert** [comment]
Install gvfs

**Comment by doihara** [comment]
It works after installing gvfs. Thank you!

**Comment by TingPing** [comment]
@baedert Can you expand on why that would be required? Gio is a complete implementation of the desktop spec and has no dependency on gvfs.

**Comment by baedert** [comment]
Ever since someone compiled Corebird for Mac and got a "Operation not supported" error every time they clicked on a link, I blame gvfs when someone posts that error message. In this case though, there was someone else on IRC with the same problem just a few days earlier and they installed gvfs out of a hunch, which solved the problem.

**Comment by ydroneaud** [comment]
On kubuntu, you could also address the issue by installing ``desktop-file-utils`` package (seen [here](https://bugs.launchpad.net/polly/+bug/1193515)).
