### ISSUE TITLE
Build-time requirements are too high to build for older distributions

### ISSUE THREAD

**Issue by probonopd** [baedert/corebird#629]
It is unnecessarily hard to build Corebird for, e.g., Ubuntu 14.04 since the required build-time dependency versions are too recent.

As a result, the trusty ppa only has an [extremely outdated version](https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/corebird?field.series_filter=trusty).

**Comment by probonopd** [comment]
Compilation on trusty fails with

```
checking for glib-compile-resources... /usr/bin/glib-compile-resources
checking for xmllint... /usr/bin/xmllint
./configure: line 12572: syntax error near unexpected token `gtksink,'
./configure: line 12572: `  GST_ELEMENT_CHECK(gtksink, 1.0, , )'
+exit 1
```

Build log: https://api.travis-ci.org/jobs/165080465/log.txt?deansi=true
Travis CI build configuration: [.travis.yml](https://github.com/probonopd/corebird/blob/patch-1/.travis.yml)

**Comment by baedert** [comment]
I don't understand what part of this is "unnecessary" or how relaxing the build-time requirements would help. The gtksink check should be disable-able using `--disable-gst-check`, but even if you do that you still need gstreamer 1.6 and gtk+ 3.18

**Comment by probonopd** [comment]
So you are saying you are not targeting users of Ubuntu 14.04 with the latest releases?

**Comment by baedert** [comment]
I don't know about the package versions in ubuntu, but if 14.04 can't satisfy those dependencies, then no.

**Comment by IBBoard** [comment]
I maintain a [patch to maintain GTK 3.16 compatibility](https://build.opensuse.org/package/view_file/home:IBBoard:desktop/corebird/corebird-gtk316.patch?expand=1) (so Corebird will build on openSUSE 42.1) but Ubuntu 14.04 is [way back on 3.10](https://distrowatch.com/table.php?distribution=ubuntu). It may work for you in a custom build or it may not.

I suspect you'll hit other issues as well, though (e.g. I had to build a newer version of gettext as well, IIRC)

**Comment by probonopd** [comment]
@IBBoard what Ubuntu version do you think could reasonably be supported?

**Comment by IBBoard** [comment]
Based on the Distrowatch list of library versions, you'll probably need at least 15.10, so you might as well go to 16.04 and get an LTS release (and you won't need my GTK 3.16 patch)

**Comment by probonopd** [comment]
True. Thanks @IBBoard

**Comment by Vistaus** [comment]
A while back, I've used Corebird on GalliumOS (switched back to Antergos/Arch soon after) which is based on 16.04 and it built and worked just fine from git master.

@baedert is right that relaxing the build requirements doesn't help. 14.04 uses an extremely outdated, upstream-unsupported version of GNOME. It'll be impossible and IMHO quite stupid to still support that unless Corebird would be (partly) rewritten to support it but that's a huge task and takes up a lot of time that could be spent on improving Corebird.
Bottom line: just upgrade to 16.04 or some other distro with at least GTK 3.18 (or 3.16 if you use IBBoard's patch) and your problem will be solved.

**Comment by probonopd** [comment]
@Vistaus ...or stay with Corebird 0.9 https://bintray.com/probono/AppImages/Corebird#files

**Comment by Vistaus** [comment]
@probonopd Yes, but then you miss out on quite some features, the most important one being longer tweets. Esp. for reading them since they *will* get cut off in older versions of Corebird.

**Comment by 20NE** [comment]
Same problem. 
Arch linux 
gtk3 3.22
 gtk2 2.24

**Comment by baedert** [comment]
And what exactly would be the problem on Arch?

**Comment by Vistaus** [comment]
I'm wondering the same thing. I'm using Arch and I have no problems building and using Corebird from git master. Which is to be expected as Corebird always supports the newest GTK releases.

**Comment by probonopd** [comment]
But people on CentOS do.

**Comment by IBBoard** [comment]
But people on CentOS are using a "built for stability" platform that is inherently *not* going to have new libraries.

I started on Linux with Redhat 7.3 before drifting through Fedora. Most people who want the Redhat goodness but modern apps and libraries go for Fedora. I'd never use CentOS as a desktop environment, except in an enterprise where you value the stability and the consistency with your servers.

Alternatively, you do what I do and maintain enough patches to be able to keep rebuilding it with minor tweaks so that it still works against older libraries. I've got Corebird build (including the new gspell dependency) for openSUSE 42.1 and newer. I also have apps and libraries that I still build for the previous release of openSUSE (13.2), in case anyone else uses them, but Corebird isn't one of them because 13.2 is just too old and too much effort to support, if it isn't trivial.

**Comment by 20NE** [comment]
arch linux building failed problem solved.
I built it with `--disable-video`  and removed all gst* deps in the PKGBUILD file. Building failed.  Even with `--disable-gst-check`.
I try to remove all gst* deps but gstreamer, building works smoothly without errors. 
Cheers.

**Comment by probonopd** [comment]
> But people on CentOS are using a "built for stability" platform that is inherently not going to have new libraries.

Correct. We still want new _applications_ though.

**Comment by IBBoard** [comment]
But if you don't have new libraries then how can you get new apps 😉 Without new libraries then your options are:
 * Find new applications that stick to old libraries (CentOS 7 uses GTK 3.14, which is over two years old and hasn't been updated in the last 15 months)
 * Try my 3.16 patch and see if it still uses any 3.16-only code that also needs patching out
 * Move to Fedora (or another distro - something nice, like openSUSE Leap 😉 Just wait a few days until 42.2 comes out)

While I agree that it'd be nice to support older distros, I'd rather have more apps for up-to-date distros and keep server-centric distros for servers. Unfortunately, I mainly blame the GTK team for this, since they iterate so quickly and change the API so frequently that the desktop space is *always* going to end up with these problems.

**Comment by probonopd** [comment]
Easy: do not assume people have the latest GTK. Develop against an older one, should still run on later ones as long as the major version has not changed.

**Comment by IBBoard** [comment]
And when the developer wants to use one of the new features or widgets or behaviours…? Should devs still be building against GTK 3.4, just because that's what Ubuntu 12.04 ships with and it isn't EOL yet? 

I'm not an experience GTK developer, but I keep an eye on things for personal interest and from what I've read then GTK has come on leaps and bounds over the versions and is only just stabilising recently. In fact, I tweak some themes and most new versions of GTK break *something*, and 3.20 just went and broke pretty much everything with a styling restructure.

**Comment by probonopd** [comment]
> And when the developer wants to use one of the new features or widgets or behaviours…? Should devs still be building against GTK 3.4, just because that's what Ubuntu 12.04 ships with and it isn't EOL yet?

Yes.

That's how developing for stable platforms works. Otherwise users on those systems will be forced to use old versions of your software.

**Comment by IBBoard** [comment]
Yikes, I would *not* like to use an app in late 2016 that only supported GTK as it was in early 2012! Those were the dark days of Gnome 3 just about finding its feet.

At the end of the day, there's stable and there's stable. Each developer picks the point they're willing to work against. Keeping up with library developments as a developer is a pain, but so is supporting old operating systems/libraries that you don't have installs of. Baedert focuses on Ubuntu (I believe) and has been rather cutting edge with some bits (hence the "GTK22" flag to support 3.18 but with optional 3.22 support) but, at the same time, focusing a desktop app on a modern desktop OS is a reasonable decision for someone to make.

As much as someone *could* still be running a desktop on Ubuntu 12.04 because it is LTS, the practicalities are that you'll miss out on so much modern stuff that you're only realistically going to stick to such an old version on a server. That's what LTS is for - stability in data centres.

If you're running CentOS 7 with GTK 3.14, have you tried building with the GTK 3.16 patch that I linked to earlier?

**Comment by marciosr** [comment]
Now that kind of problem will be less frequent. GTK 3.22.x will maintain the ABI stability, and the breaks will occur in the devel branch 3.9x (future GTK4).
There is flatpak for CentOS 7?
If yes, corebird could be bundled with a compatible gtk version.

**Comment by probonopd** [comment]
> There is flatpak for CentOS 7?
If yes, corebird could be bundled with a compatible gtk version. 

That's cheating, err, bloating. Because that way a newer GTK+ leaks into the supposedly stable base system.

**Comment by IBBoard** [comment]
The point of Flatpak is that you *don't* leak newer libraries into a stable base system. Instead you add bloat and potentially unmanaged version of libraries that have to be independently updated or else they maintain their own sets of bugs and vulnerabilities. It's kinda like the Windows way, only with a bit of sandboxing.

By sticking with CentOS 7 then you're unable to run four iterations of the newer/improved Files, Video and Photos apps, and you don't even have the Calendar, Character and Books apps. You're already sacrificing up-to-date apps for the sake of having a stable server-centric CentOS 7 distro as your desktop OS.

Have you tried any of the (now four) options that have been suggested? (1: try my GTK3.16 patch, 2: find a different app, 3: try a more modern, desktop-centric distro or 4: investigate Flatpak)

**Comment by probonopd** [comment]
@IBBoard it's not about me trying things, it's about developers who should develop for stable platforms rather than sloppily relying on the latest bleeding-edge dependencies "being there" somehow.

**Comment by marciosr** [comment]
https://github.com/gbraad/flatpak-centos-runtime

**Comment by probonopd** [comment]
@marciosr that is a workaround rather than the solution. If is like if developers assumed everyone had Windows 10 instead of developing for Windows 7, and then installing parts of Windows 10 in Windows 7 machines as a workaround.

**Comment by baedert** [comment]
*sigh*
I don't "slopply" depend ony a gtk+ version. I work on gtk+ upstream and I do that so I can use what I work on. And 3.18 is in no way "bleeding edge.

I won't port anything to an older gtk+ version so this entire thread is nonsense.

**Comment by probonopd** [comment]
@baedert sorry if you feel offended, I wasn't specifically talking of you but of _developers_ in general.

**Comment by marciosr** [comment]
Flatpak or Snappy are not workarounds but different methods of packaging and releasing apps. They permit to solve that kind of problem while let the developer work with the libs that he wants or have to use for whatever reason.    Developer has the right to control the deployment of your app updates, not being attached to a release circle of a specific distro or desktop. 

Just trying to help.

**Comment by Vistaus** [comment]
@probonopd It depends on what you call stable. The GTK versions included in them are deprecated and declared not fully stable/not fully mature by the upstream devs. Only recent GTK versions (3.18 and up) are declared nearly stable/nearly mature by the upstream devs.

**Comment by probonopd** [comment]
That sounds to me like so far only GTK+ 2 is "stable"... in the sense of "mature and can be relied on to not break"?

**Comment by Vistaus** [comment]
That's correct. GTK+ 2 is the only 100% stable and mature GTK version right now while 3.22 is 99% mature. 3.24 will be the first 100% mature GTK+ 3 version which is why they're now focusing on ABI stability. Meanwhile, GTK+ 4 (which is currently also being worked on) will be the new unstable/'immature' series for a long, long time. Until 4 is stable, 3.2x will be sort-of like a stable LTS version.

**Comment by probonopd** [comment]
@Vistaus and where is the averade app developer/user supposed to know that from? If what you are saying is correct, then application developers should have been using only 2 so far, and all "3" versions should have been called "2.99.x", with 3.2x being "3.0.0". At least if I get [semver](http://semver.org/) right. 

On a more practical side, this means that application developers should only rely on 2 and 3.2x if I understand you correctly. Everything else will lead to _breakage and frustration_.

**Comment by Vistaus** [comment]
It's up to every dev for him/herself to decide what to use. The average user isn't supposed to know this technical stuff and the average dev was supposed to know this from the changelogs which outlined the many ABI changes throughout each version. Same goes for GNOME Shell and GTK+ 3 theming btw: look at how many theme devs gave up after Shell/GTK 3.8 just because they had to re-do their theme almost from the ground up with each new Shell/GTK release. It took the Shell/GTK devs up to 3.20 to make theming full mature, which can be seen from the fact that nearly every 3.20 theme is compatible with 3.22 as well.
Yes, it should've been called 2.99.x but GTK+ and GNOME devs have their own versioning scheme. 3.18 and up is currently mature enough as the ABI hasn't changed as much as it did previously and 3.24 will be fully mature.

**Comment by marciosr** [comment]
About the new GTK+ versioning scheme: 
https://blog.gtk.org/2016/09/01/versioning-and-long-term-stability-promise-in-gtk/

**Comment by Vistaus** [comment]
And now it's official: https://github.com/baedert/corebird/commit/337fbec85adfe2cff0fb8390e749b9a39f7653b6
