### ISSUE TITLE
Unable to package corebird

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#656]
Since commit 4bb19ef13c92dc1279eb734b6c1092beb38bb95a tweetstates and accountdialog are located at the top builddir which makes it harder to package corebird because rpmbuild fails allways because these to files are installed but not packaged.

So what about these two files? Are they still required by corebird or are they temporary and can be deleted after building corebird?

**Comment by baedert** [comment]
No they aren't needed, they are just test executables I use for testing (but I'd like to keep them because it's very handy now and then).

I could set `noinst_bindir` to something else of course, like `$(abs_top_builddir)/examples` or any other directory really and I don't care, the current version was just useful and make distcheck didn't complain. What directory would work for rpmbuild?

**Comment by HeikoAdams** [comment]
The problem is that rpmbuild wants **all** files to be packaged which exist in the build-dir. So it would be helpful to move these to files to a special make target (i.e. test) so they are only build if make test was done.

**Comment by baedert** [comment]
I hope that commits works around the problem at least.

**Comment by HeikoAdams** [comment]
Yes, that killed the cat. Thanks!
