### ISSUE TITLE
Corebird loses track of "back" history 

### ISSUE THREAD

**Issue by IBBoard** [baedert/corebird#708]
For a while now I've *occasionally* been unable to use the "Back" arrow in the header bar to go all the way back to my main timeline. After having it happen randomly on several occasions, this is the first recreatable one I found. Other combinations are probably available that leave you stuck on other pages.

**Steps to recreate:** Click Mentions, double-click tweet to get tweet page, click a handle to view the profile,
click Home, click Mentions, click Back, Back, Back, Back.

(Note: Profile and Home both come in from left, whereas others come in from right. )

**Expected:** Can click back again to go to Home.

**Actual:** Back gets disabled.  Get left on Mentions.

(I'm guessing the bug is around https://github.com/baedert/corebird/blob/6cd7d1b149136cc5f10e0a4d56dc8af75014fe33/src/MainWidget.vala#L113-L150 because some pages transition in different ways and the path does re-visit pages)

**Comment by Vistaus** [comment]
Can't reproduce. What OS are you on and what Corebird version?

**Comment by baedert** [comment]
Well the history is at most 5 steps deep: https://github.com/baedert/corebird/blob/6cd7d1b149136cc5f10e0a4d56dc8af75014fe33/src/MainWidget.vala#L24
:)
A number I once made up and nobody complained so it just stayed that way. I guess that's the problem you're seeing.

**Comment by IBBoard** [comment]
That might be it 😄

Seems odd that some pages come in from the left, though!

I tend to hit it when I've checked my notifications, looked at a tweet thread, clicked "Home" to go back to my timeline, done a couple of extra bits, and then noticed that the "Back" button is enabled and (being slightly obsessive) felt the need to press "back" to clear the history!

Is there anything stopping the history being an infinite linked list of bundles, rather than a fixed array? (Other than effort, and the technical impossibility of "infinite" given finite memory!)

**Comment by baedert** [comment]
> Is there anything stopping the history being an infinite linked list of bundles, rather than a fixed array? 

Not technically I guess. It's just that the desired behavior is to keep *all* the state of a page. We do that, for example, for the TweetInfoPage by just saving the ID (or `CbTweet` object) of the tweet, but we still have to load all the replies and replied-to tweets every time you enter a page and that's rate limited, so clicking through a lot of tweets and then quickly going back will probably hit the rate limit. It's worse for the SearchPage I think since we don't save anything there so search for Foo, then for Bar and hitting back (assuming you managed to get the search page into the history twice somehow) will just show the results for Bar again even though it should show all the results for Foo.

Dunno, we can just increase from 5 to 10 or something ¯\_(ツ)_/¯

**Comment by IBBoard** [comment]
10 will probably be enough. People like me are less likely to have clicked to ten tabs and then decide they want to obsessively go back to the start so that the "back" button isn't enabled!
