### ISSUE TITLE
Utilize GTK+ Theme

### ISSUE THREAD

**Issue by justinnichols** [baedert/corebird#724]
I installed Corebird via snap on Ubuntu 16.04 with GNOME as my desktop environment.  I've installed the arc-darker GTK+ theme.  Corebird is not utilizing that theme, yet the title-bar has the look and feel of a GNOME application.  This may simply be an enhancement request as I do not know if it was ever intended to respect GTK+ themes.

**Comment by baedert** [comment]
Corebird already uses whatever desktop theme you're using, so this is Snap related and I can't help you with that anyway.

**Comment by diddledan** [comment]
this is related to Snapd's confinement. There is an ongoing discussion at https://forum.snapcraft.io/t/use-the-system-gtk-theme/496

can I ask that you make a new issue on https://github.com/diddledan/corebird-snap/issues because issues with the Corebird Snap package are my domain, so I don't want to pollute @baedert's issue tracker with things that are unique to the snap :smile:

**Comment by justinnichols** [comment]
Done, sorry I didn't know it needed to go to a specific snap place.  It's been a long time since I installed Corebird so I didn't know if it normally adhered to GTK+ themes or not.
