### ISSUE TITLE
Lookup Users to Mention

### ISSUE THREAD

**Issue by ryanleesipes** [baedert/corebird#740]
It seems like I'm having to open the web client daily to mention users who I am not following. I would love the ability to "look up" users to mention when writing a Tweet.

Any possibility that this could be implemented?

**Comment by baedert** [comment]
Yeah, that's a call to the search API so not terribly complicated. I'm just not sure how to best integrate it in the current UI, especially since the results are mostly garbage unless you can search for first+last name of a well-known person and that doesn't work with the "write an @ and then a word" system.

**Comment by Vistaus** [comment]
This is already implemented. I just tested it out with MS Data Science, who I'm not following (I didn't even know it existed until a few minutes ago) and it correctly suggests it, as you can see in the screenshot.
![screenshot from 2017-06-21 18 29 59](https://user-images.githubusercontent.com/1716229/27395371-1a088060-569f-11e7-8a45-d42ffa6e1d5e.png)

**Comment by Vistaus** [comment]
And in case you might think it's because I have opened up their Twitter profile, it's not as you can see in my second example below.

![screenshot from 2017-06-21 18 34 54](https://user-images.githubusercontent.com/1716229/27395559-b4021a64-569f-11e7-8f00-9903a1a748a5.png)
![screenshot from 2017-06-21 18 35 06](https://user-images.githubusercontent.com/1716229/27395558-b3f96536-569f-11e7-8712-3832d37135fa.png)

**Comment by baedert** [comment]
Those results are all local though and based on a list of users that you've seen already, so the completion will never list users completely unknown to you.

**Comment by Vistaus** [comment]
That's not true. For example, here's completion of @rtlnieuws which I know exists but I've never ever looked them up as I don't like them.

![screenshot from 2017-06-21 19 07 22](https://user-images.githubusercontent.com/1716229/27396965-453d6070-56a4-11e7-897d-64e5d1920239.png)

**Comment by baedert** [comment]
That's because basically the author and/or retweeter of every tweet we ever download gets cached, i.e. also all authors of all tweets in a profile you open

**Comment by Vistaus** [comment]
Ah, okay, I understand now. Thanks.

**Comment by baedert** [comment]
On further inspection, the user cache is definitely somehow broken; some IDs end up being negative and the scores don't match at all (at least I don't recall ever having seen the user with the highest score in my cache).

**Comment by baedert** [comment]
So there's a `inline-completion` branch that uses both the local user cache as well as looks up the given handle remotely. Using *only* a user search is horrible and gives shitty results unless you really spell out the entire name anyway.

That branch is also a test for inline completion that doesn't use a popup window. I'm not really happy with it at the moment.

**Comment by Vistaus** [comment]
Seems like this is implemented now, thank you so much! :)

**Comment by baedert** [comment]
The UI is debatable and will probably change, but let's close this one then.

**Comment by baedert** [comment]
Should learn to click the right button I guess...
