### ISSUE TITLE
Could not load tweets Too Many Requests

### ISSUE THREAD

**Issue by mulle-nat** [baedert/corebird#845]
Even after the great Twitter fallout, the base functionality of Corebird (at least which I am using), which is read tweets and write tweets seems to continue to work fine.

Often I get this message though

```
Could not load tweets
Too Many Requests
```
and then the tweets are hidden. It would be nice if Corebird would either

* just show this a status somewhere and make this not a modal error
* have an option to increase the poll period, so that this error doesn't occur
* just ignore this particular error message, since on a future retry it will work anyway

**Comment by lucaswerkmeister** [comment]
Seconded. I often get this error while I’m still catching up with old tweets (presumably, Corebird keeps polling for new tweets even when I’m currently scrolling through sections of my timeline several hours old), so any change that would just let me keep reading the already loaded timeline (make the error less prominent, ignore it, whatever) would be very highly appreciated.

That said, I can totally understand if there’s not much motivation to continue working on Corebird right now, and want to take this opportunity to thank @baedert for writing an excellent Twitter client, whose user experience I will probably continue to reminisce about for years – it’s not your fault Twitter is shit :(

**Comment by Vistaus** [comment]
@mulle-nat You can request whatever you want, but Timm has already made it clear that he's not going to continue working on Corebird, so I suggest you search for an alternative if any of the things mentioned are starting to bother you.

**Comment by baedert** [comment]
> have an option to increase the poll period, so that this error doesn't occur

Corebird doesn't do any polling.

> just ignore this particular error message, since on a future retry it will work anyway

So things just magically stop working and you don't know why and that's ok?


And thanks but here still won't be another release so whatever.

**Comment by lucaswerkmeister** [comment]
The following patch (against the `1.7.4` tag) seems to help a lot:

```diff
diff --git a/src/CbUserStream.c b/src/CbUserStream.c
index 275ed3cb..2425c146 100644
--- a/src/CbUserStream.c
+++ b/src/CbUserStream.c
@@ -145,7 +145,7 @@ start_heartbeat_timeout (CbUserStream *self)
   if (self->heartbeat_timeout_id != 0)
     return;
 
-  self->heartbeat_timeout_id = g_timeout_add (45 * 1000, heartbeat_cb, self);
+  self->heartbeat_timeout_id = g_timeout_add (120 * 1000, heartbeat_cb, self);
 }
 
 static void
```

Since applying it and rebuilding Corebird, i’m seeing a lot less of these errors. Hope this helps someone else as well.

**Comment by mulle-nat** [comment]
> So things just magically stop working and you don't know why and that's ok?

You could syslog it... :) 

> Corebird doesn't do any polling.

But tweaking a heartbeat period apparently does have an effect.

So I will try this patch by @lucaswerkmeister , it sounds good to me.

**Comment by Alexmitter** [comment]
@lucaswerkmeister would it be possible to you to make a fork and make a release with the patch?

**Comment by nathan2423** [comment]
I second the request from Alexmitter!  @lucaswerkmeister , I find corebird still very useful without the push updates, but I can't read backwards like I want with the refresh broken.  And it's far beyond my capabaility to patch anything.  Please consider a fork with the patch.  THANK YOU!!

**Comment by nathan2423** [comment]
Thank you Vistaus!

**Comment by Alexmitter** [comment]
@nathan2423 its not really about the patch, its more about the struggle with all the dependencies to build it yourself.
One fork that has clear code with the patch and other changes that may help. Maybe removed reference to the stuff not working since doom day of 3. party twitter clients. and make a binary release. Done. But i have to say for some reason, i myself struggle to build it, no issue applying the patch in the other hand.

**Comment by nathan2423** [comment]
@Alexmitter I now know exactly what you mean on difficulty building.  I spent a couple of hours playing and got nowhere.  Fortunately, however, one of the leaders over at MX-17 Linux (which I use) was willing to put together a deb file, as discussed in this thread - http://forum.mxlinux.org/viewtopic.php?f=134&t=43195&p=462214&sid=7a15a0ee3d20f5e247c99b8dfa36a47a#p462214  His patched version seems to be working pretty well.  It refreshes at the 2 minute mark, which really isn't ideal, but is a lot better than pre-patch.  It would be nice if someone who knows what they are doing could pick up the ball and make that adjustable, but it's far beyond my capacity.  I would REALLY appreciate @lucaswerkmeister or anyone else considering a fork, because Corebird is still the best format for reading tweets (especially on a big-screen TV where I often use it).  The pushed auto-updates may be gone, but the auto-refresh seems to sort of do the same thing, so it would be great if people could choose how frequently the auto-refresh occurs, or turn it off entirely while they are reading old tweets.  I have to think that most users are using it that way anyway.  How many of them are really just waiting for Twitter to push new posts?  Most normal people, I would think, only pick it up no more than every 15 minutes or longer (in most cases a lot longer) and then pick it up with the idea of scrolling back to see what they missed.  A fork that allowed these features would be ideal.

**Comment by lucaswerkmeister** [comment]
Okay, a fork is now live at https://github.com/lucaswerkmeister/corebird. I’ve pushed a commit that fixes this bug and also opened a few more bugs for possible improvements (though, to be clear: I have no immediate plans to work on them).

For now I’ve kept the Corebird name, but if @baedert would prefer a different name I’m sure we can find something. (Personally, I’ve always liked the “Iceweasel” joke. What would be the opposite of Corebird – Crustpenguin?)

Should I try to build packages for some package managers and publish them as a GitHub release? (I suppose that would require a new version, though, and I’m not sure how the fork should be versioned. 1.7.4-1?)

**Comment by mulle-nat** [comment]
I would appreciate a .deb package or something like this. I tried compiling Corebird on  `bionic` but I couldn't get all the build requirements right, without possibly conflicts with my regular development setup. And then gave up.

**Comment by Alexmitter** [comment]
@lucaswerkmeister Crustpenguin sounds like a Twitter client i want to use. I like the name.

>Should I try to build packages for some package managers and publish them as a GitHub release?
I would recommend to make a tarball with binary and maybe a deb file.

>and I’m not sure how the fork should be versioned. 1.7.4-1?
If you want to make a hard break from the old development with the new name, i would also begin with a new version number to clearly show the break, go for 1.0 again or 2.0 for the initial version.

**Comment by Alexmitter** [comment]
@mulle-nat 

In the last reply from @nathan2423 is a link with deb packages, just make sure you block apt from updating corebird after that by "sudo apt-mark hold corebird"

**Comment by henriknj** [comment]
@lucaswerkmeister Wouldn't it be easier to just use something like flatpak, and release to flathub?

**Comment by Alexmitter** [comment]
@henriknj actually no. Flatpak and Snap are both bad concepts because both work with a Diskimage that you have to mount. At the end you have like 20 mounts for all kinds of little apps. Applications have problems use system resources like themes. Deb is totally enough as every distro worth supporting is Debian Based. Gentoo and Arch traditionally support them self.

**Comment by henriknj** [comment]
@Alexmitter It seems like you experience stems from snap, and not flatpak, which uses ostree and not squashfs based diskimages, and work has already been done in the master repo for supporting flatpak. However, this was only a suggestion in order limit the work required by @lucaswerkmeister.

**Comment by lucaswerkmeister** [comment]
Flatpak seems like the easiest route for now, so I’ve published a 1.7.4.1 release of the fork and opened flathub/flathub#716 to request the inclusion of a `de.lucaswerkmeister.corebird` package.

**Comment by Alexmitter** [comment]
@lucaswerkmeister I would appreciate if you could add a compiled package of your release version to your GitHub release because as you only want to support flatpak, it would be impossible for me and other people who refuse to install the framework for flatpak. I would try to maintain my platform native package manager but I did not find the right system version to build it Corebird. What system do you use to compile?

**Comment by baedert** [comment]
Discuss this somewhere else.

**Comment by lucaswerkmeister** [comment]
I opened lucaswerkmeister/corebird#9 to discuss distribution mechanisms, for everything else please open new issues. @baedert feel free to lock the discussion here.
